
export const RETRIEVE_IMAGES_STARTED = 'RETREIVE_IMAGES_STARTED';
export const RETRIEVE_IMAGES_COMPLETED = 'RETRIEVE_IMAGES_COMPLETED';
export const RETRIEVE_IMAGES_FAILED = 'RETEIEVE_IMAGES_FAILED';

export const SAVE_LIST_STARTED = 'SAVE_LIST_STARTED';
export const SAVE_LIST_COMPLETED = 'SAVE_LIST_COMPLETED';
export const SAVE_LIST_FAILED = 'SAVE_LIST_FAILED';

export const RETRIEVE_LIST_STARTED = 'RETRIEVE_LIST_STARTED';
export const RETRIEVE_LIST_COMPLETED = 'RETRIEVE_LIST_COMPLETED';
export const RETRIEVE_LIST_FAILED = 'RETRIEVE_LIST_FAILED';